version: '3'
services:

  nginx:
    build: ./nginx
    image: sfeir/sf-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - scm
      - jenkins
      - sonar
      - nexus

  scm:
    build: ./scm
    image: sfeir/sf-scm-manager
    volumes:
      - scm:/home/scm

  jenkins:
    build: ./jenkins
    image: sfeir/sf-jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
    depends_on:
      - scm
      - sonar
      - nexus

  sonar:
    build: ./sonar
    image: sfeir/sf-sonar
    volumes:
      - sonar-data:/opt/sonarqube/data
    depends_on:
      - scm

  nexus:
    build: ./nexus
    image: sfeir/nexus
    volumes:
      - nexus-repo:/nexus-data

volumes:
  scm:
    driver: local
  jenkins-data:
    driver: local
  sonar-data:
    driver: local
  nexus-repo:
    driver: local
